FROM ruby:2.6.3-slim
RUN apt-get update && apt-get install -y curl nodejs npm && npm i -g yarn # Rails6用(Rails7では不要)

WORKDIR /app

COPY Gemfile Gemfile.lock ./
RUN bundle
COPY . .

ENTRYPOINT ["curl", "https://raw.githubusercontent.com/takumi3488/rails6-docker-for-review/main/lib/entrypoint.sh", "|", "bash"]

CMD ["rails", "s", "-b", "0.0.0.0"]
